version: "3.3"

services:
  db:
    container_name: postgres_db
    image: postgres:13
    restart: always

    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=chat_db
      
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
  app:
    container_name: node_app
    build:
      dockerfile: Dockerfile
      context: .
    depends_on: 
        - db
    ports:
      - 8000:8000
    volumes:
      - ./:/app
volumes:
  db:
